### ISSUE TITLE
关于“Lealone开发测试环境搭建”的问题

### ISSUE THREAD

**Issue by zbhuang** [codefollower/Lealone#73]
新手，刚开始学习Lealone。
按照这个文档，发现
1.HMasterStarter.java的目录已经不是这个了lealone-test/src/test/java/org/lealone/test/start/HMasterStarter.java，而是/lealone-test-hbase/src/test/java/org/lealone/hbase/start/HMasterStarter.java。
第二个问题，我启动HRegionServerStarter之后，运行测试用例，they all fail.
(不知道是不是我没设置正确？望赐教，谢谢)
The log in the console is the following

15/01/11 08:34:39 INFO zookeeper.ClientCnxn: Session establishment complete on server 127.0.0.1/127.0.0.1:2181, sessionid = 0x14ad9316b48000a, negotiated timeout = 40000
15/01/11 08:34:40 WARN client.HConnectionManager$HConnectionImplementation: Encountered problems when prefetch META table: 
org.apache.hadoop.hbase.TableNotFoundException: Cannot find row in .META. for table: TRANSACTIONTEST, row=TRANSACTIONTEST,,99999999999999
	at org.apache.hadoop.hbase.client.MetaScanner.metaScan(MetaScanner.java:164)
	at org.apache.hadoop.hbase.client.MetaScanner.access$000(MetaScanner.java:54)
	at org.apache.hadoop.hbase.client.MetaScanner$1.connect(MetaScanner.java:133)
	at org.apache.hadoop.hbase.client.MetaScanner$1.connect(MetaScanner.java:130)
	at org.apache.hadoop.hbase.client.HConnectionManager.execute(HConnectionManager.java:360)
	at org.apache.hadoop.hbase.client.MetaScanner.metaScan(MetaScanner.java:130)
	at org.apache.hadoop.hbase.client.MetaScanner.metaScan(MetaScanner.java:105)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.prefetchRegionCache(HConnectionManager.java:922)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegionInMeta(HConnectionManager.java:977)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegion(HConnectionManager.java:864)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegion(HConnectionManager.java:821)
	at org.apache.hadoop.hbase.client.HTable.finishSetup(HTable.java:234)
	at org.apache.hadoop.hbase.client.HTable.<init>(HTable.java:174)
	at org.apache.hadoop.hbase.client.HTable.<init>(HTable.java:133)
	at org.lealone.hbase.jdbc.transaction.TransactionTest.regions(TransactionTest.java:164)
	at org.lealone.hbase.jdbc.transaction.TransactionTest.run(TransactionTest.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
15/01/11 08:34:40 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=127.0.0.1:2181 sessionTimeout=120000 watcher=catalogtracker-on-org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation@1ce92674
15/01/11 08:34:40 INFO zookeeper.ClientCnxn: Opening socket connection to server /127.0.0.1:2181
15/01/11 08:34:40 INFO client.ZooKeeperSaslClient: Client will not SASL-authenticate because the default JAAS configuration section 'Client' could not be found. If you are not using SASL, you may ignore this. On the other hand, if you expected SASL to work, please fix your JAAS configuration.
15/01/11 08:34:40 INFO zookeeper.RecoverableZooKeeper: The identifier of this process is 127624@zbhuang_home
15/01/11 08:34:40 INFO zookeeper.ClientCnxn: Socket connection established to 127.0.0.1/127.0.0.1:2181, initiating session
15/01/11 08:34:40 INFO zookeeper.ClientCnxn: Session establishment complete on server 127.0.0.1/127.0.0.1:2181, sessionid = 0x14ad9316b48000b, negotiated timeout = 40000
15/01/11 08:34:44 INFO zookeeper.ZooKeeper: Session: 0x14ad9316b48000b closed
15/01/11 08:34:44 INFO zookeeper.ClientCnxn: EventThread shut down

**Comment by codefollower** [comment]
wiki上面的文档没有及时更新，最近一个月代码已经做了大量改动，接下来再更新开发文档。

**Comment by codefollower** [comment]
你可以在eclipse中先从lealone-test-rdbms着手，org.lealone.test.cbase包是一个独立的数据库，
不需要HBase的，里面分了三种运行模式: embedded_mode中的EmbeddedExample是可以直接运行的。

如果要试HBase的话，在lealone-test-hbase中，因为最近代码改动非常大，还有挺多错误。

**Comment by codefollower** [comment]
刚刚更新了一下wiki，
目前代码更新非常频繁，所以文档跟进速度会非常慢的。
